# Generated by Django 4.2.23 on 2025-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
