# Generated by Django 4.2.23 on 2025-09-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='app.institution')),
                ('question_banks', models.ManyToManyField(related_name='exams', to='app.questionbank')),
            ],
            options={
                'db_table': 'app_exams',
            },
        ),
        migrations.CreateModel(
            name='ApprovalCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_criteria', to='app.difficultylevel')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_criteria', to='app.exam')),
            ],
            options={
                'db_table': 'app_approval_criteria',
            },
        ),
    ]
