# Generated by Django 4.2.23 on 2025-09-08 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_exam_approvalcriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalcriteria',
            name='approval_percentage',
        ),
        migrations.RemoveField(
            model_name='approvalcriteria',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='approvalcriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalcriteria',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalcriteria',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvalcriteria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ApprovalCriteriaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.approvalcriteria')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_details', to='app.difficultylevel')),
            ],
            options={
                'db_table': 'app_approval_criteria_details',
            },
        ),
    ]
