# Generated by Django 4.2.23 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_approvalcriteria_approval_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_questions',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
