# Generated by Django 4.2.23 on 2025-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_exam_max_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalcriteriadetail',
            name='approval_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
