# Generated by Django 4.2.23 on 2025-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='start_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
