# Generated by Django 4.2.23 on 2025-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_question_end_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_statement',
            field=models.TextField(blank=True, default='Seleccione la opción que considere correcta.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_statement',
            field=models.TextField(blank=True, default='A continuación se presenta la pregunta, por favor lea con atención y seleccione la opción correcta.'),
        ),
    ]
