# Generated by Django 4.2.23 on 2025-09-15 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_attempt_current_index_attempt_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
