# Generated by Django 4.2.23 on 2025-09-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_academiclevel_academicdepartment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdepartment',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_departments', to='app.modality'),
        ),
        migrations.AlterField(
            model_name='academicdepartment',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_departments', to='app.representative'),
        ),
    ]
