# Generated by Django 4.2.23 on 2025-09-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_academicdepartment_modality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicdepartment',
            old_name='level',
            new_name='academic_level',
        ),
    ]
