# Generated by Django 4.2.23 on 2025-09-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_level_academicdepartment_academic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='option_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/questions/options/audios/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/questions/statements/audios/'),
        ),
    ]
