# Generated by Django 4.2.23 on 2025-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_answeroption_option_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='option_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/questions/options/'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/questions/options/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/questions/statements/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/questions/statements/'),
        ),
    ]
