# Generated by Django 4.2.23 on 2025-11-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_question_end_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalcriteriadetail',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='approvalcriteriadetail',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attemptanswer',
            name='attempt_question',
        ),
        migrations.RemoveField(
            model_name='attemptanswer',
            name='selected_option',
        ),
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attemptquestion',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='attemptquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='ApprovalCriteria',
        ),
        migrations.DeleteModel(
            name='ApprovalCriteriaDetail',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='AttemptAnswer',
        ),
        migrations.DeleteModel(
            name='AttemptQuestion',
        ),
    ]
