# Generated by Django 4.2.23 on 2025-11-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_approvalcriteriadetail_criteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='attempts',
            new_name='max_attempts',
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_adaptive_testing',
            field=models.BooleanField(default=True, help_text='Activar evaluación adaptativa SPRT'),
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_difficulty_progression',
            field=models.BooleanField(default=True, help_text='Permitir progresión por niveles de dificultad'),
        ),
        migrations.AddField(
            model_name='exam',
            name='enforce_time_limits',
            field=models.BooleanField(default=True, help_text='Aplicar límites de tiempo estrictos'),
        ),
        migrations.CreateModel(
            name='ExamSPRTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p0', models.FloatField(default=60.0, help_text='Probabilidad mínima aceptable de competencia (%)')),
                ('p1', models.FloatField(default=40.0, help_text='Probabilidad de incompetencia (%)')),
                ('alpha', models.FloatField(default=0.1, help_text='Probabilidad de error tipo I (rechazar H0 cuando es verdadera)')),
                ('beta', models.FloatField(default=0.1, help_text='Probabilidad de error tipo II (aceptar H0 cuando es falsa)')),
                ('min_questions_per_level', models.PositiveIntegerField(default=3, help_text='Mínimo de preguntas por nivel antes de avanzar')),
                ('success_threshold_to_advance', models.FloatField(default=0.7, help_text='Porcentaje de aciertos para avanzar al siguiente nivel (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprt_config', to='app.exam')),
            ],
            options={
                'db_table': 'app_exam_sprt_configs',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'En Progreso'), ('approved', 'Aprobado'), ('failed', 'Reprobado'), ('abandoned', 'Abandonado')], default='in_progress', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('s_index', models.FloatField(default=0.0)),
                ('s_history', models.JSONField(default=list, help_text='Lista de valores S en cada pregunta')),
                ('consistency_feedback', models.CharField(blank=True, choices=[('positive', 'Consistente Positivo'), ('negative', 'Consistente Negativo'), ('inconsistent', 'Inconsistente'), ('insufficient', 'Datos Insuficientes')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('level_analysis', models.JSONField(default=dict, help_text='Análisis detallado por nivel de dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_difficulty_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='app.difficultylevel')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_exam_attempts',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'exam', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField()),
                ('question_shown_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField()),
                ('allowed_time_seconds', models.PositiveIntegerField()),
                ('time_violation', models.BooleanField(default=False, help_text='Si el tiempo excedió el permitido')),
                ('s_index_after', models.FloatField(help_text='Valor del índice S después de esta respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.examattempt')),
                ('difficulty_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.difficultylevel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='app.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='app.answeroption')),
            ],
            options={
                'db_table': 'app_attempt_answers',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('s_index', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('passed_to_next_level', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='app.examattempt')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.difficultylevel')),
            ],
            options={
                'db_table': 'app_level_progress',
                'unique_together': {('attempt', 'difficulty_level')},
            },
        ),
    ]
