# Generated by Django 4.2.23 on 2026-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_attempts_exam_max_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='enable_adaptive_testing',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='enable_difficulty_progression',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='enforce_time_limits',
        ),
        migrations.AddField(
            model_name='exam',
            name='a',
            field=models.FloatField(default=0.1, help_text='Margen de error falsos positivos (a)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='b',
            field=models.FloatField(default=0.1, help_text='Margen de error falsos negativos (b)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='p0',
            field=models.FloatField(default=60.0, help_text='Umbral de competencia esperado (P0)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='p1',
            field=models.FloatField(default=40.0, help_text='Umbral de conocimiento inaceptable (P1)'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='option_audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/options/audio/'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/options/image/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/statements/audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/statements/image/'),
        ),
    ]
