# Generated by Django 4.2.23 on 2026-09-16 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_exam_enable_adaptive_testing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Tiempo tomado en segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_attempt_responses',
            },
        ),
        migrations.RemoveField(
            model_name='examsprtconfig',
            name='exam',
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='levelprogress',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='levelprogress',
            name='difficulty_level',
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={},
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='correct_answers',
            new_name='correct_count',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='s_index',
            new_name='current_s_index',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='completed_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='incorrect_answers',
            new_name='incorrect_count',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='total_questions',
            new_name='questions_answered',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='s_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En Progreso'), ('passed', 'Aprobado'), ('failed', 'Reprobado')], default='in_progress', max_length=20),
        ),
        migrations.DeleteModel(
            name='AttemptAnswer',
        ),
        migrations.DeleteModel(
            name='ExamSPRTConfig',
        ),
        migrations.DeleteModel(
            name='LevelProgress',
        ),
        migrations.AddField(
            model_name='attemptresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.examattempt'),
        ),
        migrations.AddField(
            model_name='attemptresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question'),
        ),
        migrations.AddField(
            model_name='attemptresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.answeroption'),
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='consistency_feedback',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='current_difficulty_level',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='last_activity_at',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='level_analysis',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='session_token',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='updated_at',
        ),
    ]
